# -*- coding: utf-8 -*-
"""Seaborn.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16kGBuF4UxO6wIzR92pC92KhsVo3uobqv

# **Seaborn**
"""

from google.colab import files
files.upload()

import pandas as pd
df=pd.read_csv('train.csv')

df.head()

import matplotlib.pyplot as plt
not_Survived_df = pd.DataFrame({'Male':df[(df['Survived']==0)& (df['Sex']=='male')]['Pclass'].value_counts(),
                                'Female':df[(df['Survived']==0)& (df['Sex']=='female')]['Pclass'].value_counts()})
Survived_df = pd.DataFrame({'Male':df[(df['Survived']==1)& (df['Sex']=='male')]['Pclass'].value_counts(),
                                'Female':df[(df['Survived']==1)& (df['Sex']=='female')]['Pclass'].value_counts()})

df[(df['Survived']== 0)& (df['Sex']=='male')]['Pclass'].value_counts()

not_Survived_df

Survived_df

fig,axes=plt.subplots(nrows=1,ncols=2,figsize=(10,6))
not_Survived_df.plot(kind='bar',title='Not Survived',ax=axes[0],yticks=range(0,351,50)) #ซ้าย axes[0]
Survived_df.plot(kind='bar',title='Survived',ax=axes[1],yticks=range(0,351,50)) #ขวามือ axes[1]

import seaborn as sb

sb.catplot(x='Pclass',hue='Sex',col='Survived',kind='count',data = df)
#แกน X ด้วย Pclass hue คือ สี ตามเพศ ด้วยการนับ Kind ด้วย Data ที่มาจาก DatataFrame

from google.colab import files
files.upload()

import pandas as pd
df=pd.read_csv('Iris.csv')
df

df.head()

df['Species'].value_counts()

df.columns

sb.scatterplot(data=df,x='SepalLengthCm',y='SepalWidthCm',hue='Species')

sb.scatterplot(data=df,x='PetalLengthCm',y='PetalWidthCm',hue='Species')

